### ISSUE TITLE
Unable to set MQTT password

### ISSUE THREAD

**Issue by wayne-love** [wayne-love/sn_esp32#11]
Hi Wayne. Thanks for the reply.

I do have a dc-dc converter attached now, so all good on that front.

Turns out iv been pressing EN all this time which just resets.
To all others with a similar board you need to press BOOT to get it into hotspot mode to enter details.

Interestingly upon next boot I'm still seeing the same littlefs errors.
But it does connect to the wifi.

Which brings me to my next issue :D , where can I enter my MQTT password as I see there is only an entry for server/port?

Side note, when I enable hotspot again, wifi details are saved fine, but Mqtt server is set back to 'Mqtt' is that normal?

_Originally posted by @SCUZNUTS in https://github.com/wayne-love/sn_esp32/issues/10#issuecomment-1092126023_

**Comment by wayne-love** [comment]
This is easy.... you can't at the moment.  I can add this to the UI easy enough but will no be in a position to do any coding for about a month.  Apologies.

**Comment by SCUZNUTS** [comment]
Heads up;

Mosquitto broker add-on changelog
"6.0.0
Support for anonymous logins has been removed"

**Comment by wayne-love** [comment]
<sigh> Why do they do this.  Ok, noted. Thanks.

**Comment by JohanAlvedal** [comment]
Any progress here?

**Comment by wayne-love** [comment]
Just for information, my limited free time is now focused on https://github.com/wayne-love/SpaNetInterface which is a total rewrite of the spanet library.  Things are going slow simply because I cannot justify spending a lot of time on a system that meets 99% of my needs.  Happy for someone to submit a pull request to address this problem but I have no plans to commit time to this at the moment.

**Comment by JohanAlvedal** [comment]
Ok what you are working with is something that is independent from the SpaNet MQTT ESP32 bridge

**Comment by wayne-love** [comment]
Correct. The new project is a total re-factor of the code to delink the SpaNet interface from the actual implementation code. This will allow the SpaNET library to be integrated into any project without any dependencies on MQTT or home assistant. On 12 Aug 2023, at 12:27 am, AlvJohan ***@***.***> wrote:﻿
Ok what you are working with is something that is independent from the SpaNet MQTT ESP32 bridge

**Comment by SCUZNUTS** [comment]
That sounds exciting. I do want to use esphome and pop the spa code into that. 
so we can update everything remotely.  
Home Assistant is now complaining device and entity names are the same so I have to revisit this too

**Comment by wayne-love** [comment]
Just added MQTT username and password options to the migration branch.  Note that I've not tested extensively so please let me know if any issues arrise.
