### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by pinpong** [wayne-love/sn_esp32#16]
Discord link is not working.

**Comment by wayne-love** [comment]
Works for me. Can you provide more information?

**Comment by mekenthompson** [comment]
@wayne-love The permissions of that server/channel aren't public by the looks: 
![image](https://github.com/wayne-love/sn_esp32/assets/8923913/12c9f4c5-16f4-417f-9ee2-aaa875a4a7d7)

**Comment by simplex303** [comment]
Link doesn't work for me either. 
Doesn't take me to server/channel.

**Comment by pinpong** [comment]
@wayne-love please update the disqord link

**Comment by wayne-love** [comment]
Try this link and let me if this works https://discord.gg/pTD95rQh
