### ISSUE TITLE
Auto or configurable way to exclude entities?

### ISSUE THREAD

**Issue by TommySharpNZ** [wayne-love/sn_esp32#54]
Could we implement some way to only include devices and sensors that are installed in the spa unit?
I don't have a heat pump or auxillary heater...
Ideally some way to auto exclude them, but possibly even just somethign in the config using the web interface?

![image](https://github.com/user-attachments/assets/e65d03c9-8b8c-46b5-a67d-2644bf8b7438)

**Comment by lucasnz** [comment]
Aux Heat actually means use the "standard" heating element in combination with the heatpump. So both these settings are easily excluded if no heatpump is present... The blower is harder, I don't know if there is a data point that indicates presence. So, we could have an option in the WebUI to disable them. Of course, you can just disable them in HA.

**Comment by lucasnz** [comment]
Note to self, if we do this, we should hide current and KWh for SVM1 and SVM2 that can't measure current (unless a ct clamp is present - if we ever get to making that work).

**Comment by lucasnz** [comment]
The commit will hide the heat pump (if not connected) and current values for SVM1 & 2 that can't measure current. https://github.com/lucasnz/sn_esp32/commit/c40c7da90b2a6d0396e2192f108b5fc64b92aef7

**Comment by TommySharpNZ** [comment]
Awesome!

**Comment by lucasnz** [comment]
This is partially implemented (heat pump will not publish if it is not installed). I think the remaining we're not resolving, and saying end-users can disable entities within HA.
