### ISSUE TITLE
Determine Manufacturer and Model?

### ISSUE THREAD

**Issue by TommySharpNZ** [wayne-love/sn_esp32#55]
This is just my OCD kicking in but being able to set these values properly would be cool.
![image](https://github.com/user-attachments/assets/fc4cb331-359f-408b-8a79-5c7ed808a543)

**Comment by lucasnz** [comment]
We can pull the controller model e.g. SVM1 or SV3 and assume the manufacturer of "SpaNet" - as that what you mean? The controller doesn't provide info on the specific model of Spa pool.

**Comment by TommySharpNZ** [comment]
Yeah just the controller model and "SpaNet" as the manufacturer.

**Comment by lucasnz** [comment]
The following fields could be added as standard for all mqtt entities:
| Attribute | Description |
| -- |-- |
| configuration_url string (Optional) | A link to the webpage that can manage the configuration of this device. Can be either an http://, https:// or an internal homeassistant:// URL. |
| manufacturer string (Optional) | The manufacturer of the device. |
| model string (Optional) | The model of the device. |
| serial_number string (Optional) | The serial number of the device. |
| sw_version string (Optional) | The firmware version of the device. |

https://developers.home-assistant.io/docs/device_registry_index/#device-properties

**Comment by lucasnz** [comment]
This was simple:
![image](https://github.com/user-attachments/assets/f952dc42-f9e9-4ad1-a71d-a90dc7ca357f)

It might be good to expose the software version. But we haven't put the this into the compiled version yet... Unless we want to expose the software version of the controller.

Putting the configuration url in is handy, as it adds a link on the device page in HA:
![image](https://github.com/user-attachments/assets/df446ddf-806d-4d43-b57d-0a6faee43804)

Thoughts? https://github.com/lucasnz/sn_esp32/commit/cb80ac2eae816b720dd65a87de4017669bc4a023

**Comment by TommySharpNZ** [comment]
Yeah all good stuff!

**Comment by lucasnz** [comment]
I think we can close this now.

**Comment by TommySharpNZ** [comment]
Cool, yip I see this now in Home Assistant.
![image](https://github.com/user-attachments/assets/7a998b8d-f240-4df2-af25-5034c456d864)

![image](https://github.com/user-attachments/assets/a17ab955-58c4-421f-ae35-2309f8e17580)
